### PR TITLE
Update index.js 

### PR DESCRIPTION
**Pull request by limxuan**
There is a weird thing where you send an embed which is called embed it'll throw (Cannot send an empty message). So I just used the embed property instead.

### CODE REVIEW

**Comment by Terra-rian** [comment]
> There is a weird thing where you send an embed which is called embed it'll throw (Cannot send an empty message). So I just used the embed property instead.

What do you mean by that? Does the package generate an empty embed? Or is it something else that I'm not aware of?

**Comment by limxuan** [comment]
Try it for yourself, it will throw an error `Cannot send an empty message` the way to overcome it is by using the embed property

**Comment by Terra-rian** [comment]
Alright, I'll take a look, and most likely merge this today. Thank you!

**Edit:** I've tried to recreate any errors, and nothing popped up. I'll keep this open, if there are more issues about this I'll merge this pull request.

**Comment by Terra-rian** [comment]
Added this to upcoming the upcoming version 1.0.7, gonna close this because I don't want to have to have merge conflicts.

**Pull request closed without merging**
